name: Hello World!
on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Display the date
        run: date "+%A, %B %d, %Y at %T"

      - name: Directory content
        run: ls -l

